### ISSUE TITLE
Image URL points to placeholder.com

### ISSUE THREAD

**Issue by ndkv** [dylanatsmith/betterplaceholder#5]
Hello, 

the image URL points to placeholder.com instead of betterplaceholder.com. 

Is this meant to meant to be? 

I noticed it while developing because the images started timing out, see e.g. https://via.placeholder.com/600x400.

**Comment by dylanatsmith** [comment]
Thanks for the report. This URL was intentional as I was piggybacking off [placeholder.com](https://placeholder.com/)’s placeholder image URL schema, but it looks like that domain has been acquired and the service may not be maintained anymore.

This isn’t the first time it’s been unreliable and there are a handful of similar services I’ve considered integrating into the same UI, some with more/better options.

For now I’ve replaced the service with [fakeimage.pl](https://fakeimg.pl/) which has 1-to-1 feature parity except their default typeface is different.

I will also try to add some of their additional features (typeface, font size, etc) in the near future.
